config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :workdays do
	member do
		get 'ending'
	end 
  end
root 'workdays#index'
	

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/workday.rb
class Workday < ActiveRecord::Base
belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with name: "jonny", password: "cHGGe6l7auCV"
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :workday_id)
    end
end

app/controllers/workdays_controller.rb
class WorkdaysController < ApplicationController
  before_action :set_workday, only: [:show, :edit, :update, :destroy, :ending]

  # GET /workdays
  # GET /workdays.json
  def index
    @workdays = Workday.all.reverse
  end

  # GET /workdays/1
  # GET /workdays/1.json
  def show
  end

  # GET /workdays/new
  def new
    @workday = Workday.new
  end

  # GET /workdays/1/edit
  def edit
  end

  # POST /workdays
  # POST /workdays.json
  def create
    @workday = Workday.new(workday_params)
    @workday.start_time = Time.zone.now

    respond_to do |format|
      if @workday.save
        format.html { redirect_to workdays_path, notice: 'Workday was successfully created.' }
        format.json { render :show, status: :created, location: @workday }
      else
        format.html { render :new }
        format.json { render json: @workday.errors, status: :unprocessable_entity }
      end
    end
  end

  def ending
    @workday.end_time = Time.zone.now
	@workday.save
	redirect_to workdays_path, notice: 'Workday finished.'
  end

  # PATCH/PUT /workdays/1
  # PATCH/PUT /workdays/1.json
  def update
    respond_to do |format|
      if @workday.update(workday_params)
        format.html { redirect_to workdays_path, notice: 'Workday was successfully updated.' }
        format.json { render :show, status: :ok, location: @workday }
      else
        format.html { render :edit }
        format.json { render json: @workday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workdays/1
  # DELETE /workdays/1.json
  def destroy
    @workday.destroy
    respond_to do |format|
      format.html { redirect_to workdays_url, notice: 'Workday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workday
      @workday = Workday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workday_params
      params.require(:workday).permit(:start_time, :end_time, :category_id, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/workdays_helper.rb
module WorkdaysHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :workday_id %>
    <%= f.number_field :workday_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Workday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.workday_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Workday:</strong>
  <%= @category.workday_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Worktime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <div class="navbar-header">
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
	  <%= link_to 'Lohnarbeit', root_path, class: 'navbar-brand'%>
  </div>
  <div class="navbar-collapse collapse" id="navbar">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
	  <li class="nav-item">
				<%= link_to 'Neu', new_workday_path, class: 'nav-link btn btn-dark'%>
		</li>
	  <li class="nav-item">
				<%= link_to 'Übersicht', workdays_path, class: 'nav-link btn btn-dark'%>
		</li>
	  <li class="nav-item">
				<%= link_to 'Kategorien', categories_path, class: 'nav-link btn btn-dark'%>
		</li>
  </ul>
 </div>
</nav>
<div class="container">
<div class="container-fluid">
<%= yield %>
</div>
</div>

</body>
</html>

app/views/workdays/_form.html.erb
<%= form_for(@workday) do |f| %>
  <% if @workday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workday.errors.count, "error") %> prohibited this workday from being saved:</h2>

      <ul>
      <% @workday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <% if @workday.end_time %>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
<% end %>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, Category.all.map{|c| [c.title, c.id]}, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workdays/edit.html.erb
<h1>Editing Workday</h1>

<%= render 'form' %>

<%= link_to 'Show', @workday %> |
<%= link_to 'Back', workdays_path %>

app/views/workdays/index.html.erb
<% if notice %>
<br />
<div class="alert alert-warning alert-dismissible fade show" role="alert" id="notice">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<h1>Listing Workdays <i class="fa fa-camera-retro"></i></h1>


    <% @workdays.group_by{ |day| day.start_time.strftime("%B %Y")}.each do |group, workdays| %>
		<div class="alert alert-success">
				<% total_time = (workdays.select{|day| !day.end_time.nil? and !day.start_time.nil?}.map{|day| (day.end_time.to_f - day.start_time.to_f) }.inject(0,:+).to_i.abs)%>
				<strong><%= group%> - Total</strong>: <%= total_time / 60 / 60%>h <%= total_time / 60 % 60 %>m
		</div>
		<div class="table-responsive">
		<table class="table">
		  <thead>
			<tr>
			  <th>Date</th>
			  <th>Duration</th>
			  <th>Type</th>
			  <th colspan="1"></th>
			</tr>
		  </thead>
		<tbody>
		<% workdays.each do |workday| %>
			  <tr <%= 'style="background-color: lightgrey"'.html_safe if workday.start_time.try(:strftime, "%V").to_i % 2 == 0 %> >
			   <td><%= workday.start_time.try(:strftime,"%d.%m.%Y") %></td>
				<% if workday.end_time? %>
					<td><%= distance_of_time_in_words(workday.end_time - workday.start_time) %></td>
				<% else %>
					<td><i>Running</i></td>
				<% end %>
				<td><%= workday.category.title %></td>
				<td><%= link_to 'End', ending_workday_path(workday), class: 'btn btn-sm btn-dark' if workday.end_time.nil?%></td>
				<td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_workday_path(workday), class: 'btn btn-sm btn-dark' %>
				<%= link_to '<i class="fa fa-trash"></i>'.html_safe, workday, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-dark' %></td>
			  </tr>
		<% end %>
		</tbody>
		</table>
		</div>
    <% end %>

app/views/workdays/new.html.erb
<h1>New Workday</h1>

<%= form_for(@workday) do |f| %>
  <% if @workday.errors.any? %>
    <div id="alert alert-danger">
      <h2><%= pluralize(@workday.errors.count, "error") %> prohibited this workday from being saved:</h2>

      <ul>
      <% @workday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, Category.all.map{|c| [c.title, c.id]}, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment, class: 'form-control' %>
  </div>
  <div>
    <br />
    <%= f.submit 'Submit', class: 'btn btn-dark' %>
  </div>
<% end %>


<%= link_to 'Back', workdays_path %>

app/views/workdays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @workday.start_time %>
</p>

<p>
  <strong>End:</strong>
  <%= @workday.end_time %>
</p>

<p>
  <strong>Type:</strong>
  <%= @workday.category %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @workday.comment %>
</p>

<%= link_to 'Edit', edit_workday_path(@workday) %> |
<%= link_to 'Back', workdays_path %>